// This file will be auto-generated by running: npm run supabase:types
// After starting Supabase locally with: npx supabase start
// Then run: npx supabase gen types typescript --local > src/types/database.types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      posts: {
        Row: {
          id: string
          user_id: string
          post_id: string
          platform: 'twitter' | 'instagram' | 'tiktok' | 'youtube'
          user_handle: string | null
          user_name: string | null
          user_avatar: string | null
          text: string | null
          media: Json
          like_count: number
          view_count: number
          tags: string[]
          auto_tags: string[]
          captured_at: string
          source: string
          source_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          post_id: string
          platform?: 'twitter' | 'instagram' | 'tiktok' | 'youtube'
          user_handle?: string | null
          user_name?: string | null
          user_avatar?: string | null
          text?: string | null
          media?: Json
          like_count?: number
          view_count?: number
          tags?: string[]
          auto_tags?: string[]
          captured_at?: string
          source?: string
          source_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          post_id?: string
          platform?: 'twitter' | 'instagram' | 'tiktok' | 'youtube'
          user_handle?: string | null
          user_name?: string | null
          user_avatar?: string | null
          text?: string | null
          media?: Json
          like_count?: number
          view_count?: number
          tags?: string[]
          auto_tags?: string[]
          captured_at?: string
          source?: string
          source_url?: string | null
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      get_user_stats: {
        Args: {
          stats_user_id: string
        }
        Returns: Json
      }
      search_posts: {
        Args: {
          search_user_id: string
          search_query?: string
          search_platforms?: string[]
          search_tags?: string[]
          limit_count?: number
        }
        Returns: {
          id: string
          post_id: string
          platform: 'twitter' | 'instagram' | 'tiktok' | 'youtube'
          user_handle: string | null
          text: string | null
          captured_at: string
          tags: string[]
          relevance: number
        }[]
      }
    }
    Enums: {
      platform_type: 'twitter' | 'instagram' | 'tiktok' | 'youtube'
    }
  }
}
